# Generated by Django 3.1.6 on 2021-02-06 09:23

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePlanModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availableCourse', models.CharField(max_length=100, null=True)),
                ('attemptedCourse', models.CharField(max_length=100, null=True)),
                ('createdPlan', models.DateField(auto_now_add=True)),
                ('updatedPlan', models.DateField(auto_now=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'In-Active')])),
            ],
        ),
        migrations.CreateModel(
            name='courseReferenceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseType', models.CharField(choices=[('TimeBased', 'TimeBased'), ('AttemptBased', 'AttemptBased')], max_length=100, null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Existed'), (0, 'Deleted')])),
            ],
        ),
        migrations.CreateModel(
            name='coursesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(choices=[('JEE Mains', 'JEE Mains'), ('JEE Advance', 'JEE Advance'), ('AIIMS', 'AIIMS')], max_length=100, null=True)),
                ('extraCourse', models.CharField(max_length=100, null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Existed'), (0, 'Deleted')])),
            ],
        ),
        migrations.CreateModel(
            name='demoUserRegistrationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('mobile', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('package', models.CharField(max_length=30, null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'In-Active')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='subjectsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(choices=[('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Maths', 'Maths')], max_length=200, null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Existed'), (0, 'Deleted')])),
                ('course_id', models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentexams.coursesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='userRegistrationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, null=True)),
                ('lastname', models.CharField(max_length=100, null=True)),
                ('username', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('mobile', models.CharField(max_length=30, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('deletedDate', models.DateTimeField(auto_now=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('loginDateTime', models.DateTimeField(auto_now=True)),
                ('logoutDateTime', models.DateTimeField(auto_now=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'In-Active')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='topicsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicName', models.CharField(max_length=200, null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Existed'), (0, 'Deleted')])),
                ('course_id', models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentexams.coursesmodel')),
                ('subject_id', models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentexams.subjectsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='subTopicsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subTopicName', models.CharField(max_length=200, null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Existed'), (0, 'Deleted')])),
                ('course_id', models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentexams.coursesmodel')),
                ('subject_id', models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentexams.subjectsmodel')),
                ('topic_id', models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentexams.topicsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='subscriptionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('deletedDate', models.DateTimeField(auto_now=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'In-Active')])),
                ('courseType', models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentexams.coursereferencemodel')),
                ('userId', models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentexams.userregistrationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='subscriptionDetailsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badges', models.CharField(choices=[('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], max_length=100, null=True)),
                ('subscriptionStartDate', models.DateField(auto_now_add=True)),
                ('subscriptionEndDate', models.DateField(auto_now=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'In-Active')])),
                ('courseType', models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentexams.coursereferencemodel')),
                ('userId', models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentexams.userregistrationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='studentResultModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.PositiveIntegerField(null=True)),
                ('exam_date', models.DateTimeField()),
                ('createdResult', models.DateField(auto_now_add=True)),
                ('updatedResult', models.DateField(auto_now=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Existed'), (0, 'Deleted')])),
                ('student_id', models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentexams.userregistrationmodel')),
                ('subject_id', models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentexams.subjectsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='questionTypesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionType', models.CharField(choices=[('Numerical', 'Numerical'), ('MCQ', 'MCQ'), ('Single MCQ', 'Single MCQ'), ('Multiple MCQ', 'Multiple MCQ')], max_length=200, null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Existed'), (0, 'Deleted')])),
                ('course_id', models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentexams.coursesmodel')),
                ('subTopic_id', models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentexams.subtopicsmodel')),
                ('subject_id', models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentexams.subjectsmodel')),
                ('topic_id', models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentexams.topicsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='questionsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=1000, null=True)),
                ('c1', models.CharField(max_length=200)),
                ('c2', models.CharField(max_length=200)),
                ('c3', models.CharField(max_length=200)),
                ('c4', models.CharField(max_length=200)),
                ('answer', multiselectfield.db.fields.MultiSelectField(choices=[('c1', 'c1'), ('c2', 'c2'), ('c3', 'c3'), ('c4', 'c4')], max_length=11)),
                ('marks', models.PositiveIntegerField(default=0)),
                ('Complexity', models.CharField(choices=[('Easy', 'Easy'), ('Average', 'Average'), ('Tough', 'Tough'), ('Very Tough', 'Very Tough')], max_length=50, null=True)),
                ('course_id', models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentexams.coursesmodel')),
                ('subTopic_id', models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentexams.subtopicsmodel')),
                ('subject_id', models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentexams.subjectsmodel')),
                ('topic_id', models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentexams.topicsmodel')),
                ('type_id', models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentexams.questiontypesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='imageQuestionsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageQuestion', models.ImageField(upload_to='questions/')),
                ('img1', models.ImageField(upload_to='questions/')),
                ('img2', models.ImageField(upload_to='questions/')),
                ('img3', models.ImageField(upload_to='questions/')),
                ('img4', models.ImageField(upload_to='questions/')),
                ('answer', multiselectfield.db.fields.MultiSelectField(choices=[('img1', 'img1'), ('img2', 'img2'), ('img3', 'img3'), ('img4', 'img4')], max_length=19)),
                ('marks', models.PositiveIntegerField(default=0)),
                ('Complexity', models.CharField(choices=[('Easy', 'Easy'), ('Average', 'Average'), ('Tough', 'Tough'), ('Very Tough', 'Very Tough')], max_length=50, null=True)),
                ('topic_id', models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentexams.topicsmodel')),
                ('type_id', models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentexams.questiontypesmodel')),
            ],
            options={
                'db_table': 'imageQuestionsModel',
            },
        ),
        migrations.CreateModel(
            name='goldPlanModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('gold_id', models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentexams.subscriptiondetailsmodel')),
                ('student_id', models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentexams.userregistrationmodel')),
            ],
        ),
        migrations.AddField(
            model_name='coursesmodel',
            name='student_id',
            field=models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentexams.userregistrationmodel'),
        ),
    ]
